// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'Features/Explore/domain/entities/recent_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 6277636253294436560),
      name: 'RecentEntity',
      lastPropertyId: const obx_int.IdUid(5, 7869979005918673812),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 7242108671968316792),
            name: 'id',
            type: 6,
            flags: 129),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 459605101952463165),
            name: 'tite',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 6540176753882396589),
            name: 'price',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 3551657295991959412),
            name: 'image',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 7869979005918673812),
            name: 'uitId',
            type: 6,
            flags: 40,
            indexId: const obx_int.IdUid(1, 1418553132913428466))
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(1, 6277636253294436560),
      lastIndexId: const obx_int.IdUid(1, 1418553132913428466),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    RecentEntity: obx_int.EntityDefinition<RecentEntity>(
        model: _entities[0],
        toOneRelations: (RecentEntity object) => [],
        toManyRelations: (RecentEntity object) => {},
        getId: (RecentEntity object) => object.id,
        setId: (RecentEntity object, int id) {
          object.id = id;
        },
        objectToFB: (RecentEntity object, fb.Builder fbb) {
          final titeOffset =
              object.tite == null ? null : fbb.writeString(object.tite!);
          final priceOffset =
              object.price == null ? null : fbb.writeString(object.price!);
          final imageOffset =
              object.image == null ? null : fbb.writeString(object.image!);
          fbb.startTable(6);
          fbb.addInt64(0, object.id ?? 0);
          fbb.addOffset(1, titeOffset);
          fbb.addOffset(2, priceOffset);
          fbb.addOffset(3, imageOffset);
          fbb.addInt64(4, object.uitId);
          fbb.finish(fbb.endTable());
          return object.id ?? 0;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final titeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final priceParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 8);
          final imageParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 10);
          final uitIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final object = RecentEntity(
              tite: titeParam,
              price: priceParam,
              image: imageParam,
              uitId: uitIdParam)
            ..id =
                const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 4);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [RecentEntity] entity fields to define ObjectBox queries.
class RecentEntity_ {
  /// see [RecentEntity.id]
  static final id =
      obx.QueryIntegerProperty<RecentEntity>(_entities[0].properties[0]);

  /// see [RecentEntity.tite]
  static final tite =
      obx.QueryStringProperty<RecentEntity>(_entities[0].properties[1]);

  /// see [RecentEntity.price]
  static final price =
      obx.QueryStringProperty<RecentEntity>(_entities[0].properties[2]);

  /// see [RecentEntity.image]
  static final image =
      obx.QueryStringProperty<RecentEntity>(_entities[0].properties[3]);

  /// see [RecentEntity.uitId]
  static final uitId =
      obx.QueryIntegerProperty<RecentEntity>(_entities[0].properties[4]);
}
